title: Header Files
author: Carlos Buchart
email: cbuchart@gmail.com
description: template&lt;class Cpp, class Qt, class ... Y_Mas&gt;
show_excerpts: true
paginate: 16
paginate_path: "page:num/"
encoding: UTF-8

sass:
  sass_dir: _sass

plainwhite:
  name: Header Files
  tagline: template&lt;class Cpp, class Qt, class ... Y_Mas&gt;
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: false
  portfolio_image: "assets/portfolio.png"
  html_lang: "es"
  disqus_shortname: "headerfiles"
  condensed_mobile:
    - home
    - page
    - post
  navigation:
    - title: Carlos Buchart
      url: "https://cbuchart.com"
    - title: Código
      url: https://github.com/BlogHeaderFiles/SourceCode
    - title: Créditos
      url: "/pages/creditos"
  social_links:
    github: cbuchart
    linkedIn: in/cbuchart
    stackoverflow: 1485885/cbuchart

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
