url: https://blogheaderfiles.github.io/
title: Header Files
author: Carlos Buchart
email: cbuchart@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  template&lt;class Cpp, class Qt, class ... Y_Mas&gt;
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Header Files
  tagline: template&lt;class Cpp, class Qt, class ... Y_Mas&gt;
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  search: true # set to true to enable searchbar
  dark_mode: false # set to true to add dark mode toggle
  portfolio_image: "assets/portfolio.png" # the path from the base directory of the site to the image to display (no / at the start)
  html_lang: "es" # set the lang attribute of the <html> tag for the pages. See here for a list of codes: https://www.w3schools.com/tags/ref_country_codes.asp
  condensed_mobile:
    - home
    - page
    - post
  navigation:
    - title: Carlos Buchart
      url: "https://cbuchart.com"
    - title: Créditos
      url: "/pages/creditos"
  social_links:
    twitter: carlosbuchart
    github:  cbuchart
    linkedIn: in/cbuchart
    #rss: rss
    #dribbble: jekyll
    #flickr:   jekyll
    #instagram: jekyll
    #pinterest: jekyll
    #youtube: jekyll
    #facebook: jekyll
    #soundcloud: jekyll
    #telegram: jekyll
    #gitlab: jekyll
    #email: jekyll
    stackoverflow: 1485885/cbuchart

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - credits.md

# Build settings

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
