url: https://blogheaderfiles.github.io
title: Header Files
author: Carlos Buchart
email: cbuchart@gmail.com
description: template&lt;class Cpp, class Qt, class ... Y_Mas&gt;
show_excerpts: true

sass:
  sass_dir: _sass

plainwhite:
  name: Header Files
  tagline: template&lt;class Cpp, class Qt, class ... Y_Mas&gt;
  date_format: "%b %-d, %Y"
  sitemap: true
  search: true
  dark_mode: false
  portfolio_image: "assets/portfolio.png"
  html_lang: "es"
  condensed_mobile:
    - home
    - page
    - post
  navigation:
    - title: Carlos Buchart
      url: "https://cbuchart.com"
    - title: Créditos
      url: "/pages/creditos"
  social_links:
    twitter: carlosbuchart
    github:  cbuchart
    linkedIn: in/cbuchart
    stackoverflow: 1485885/cbuchart


plugins:
  - jekyll-seo-tag
#  - jekyll-feed
